version: '3.1'

services:
  db_postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: secretPassw0rd
      POSTGRES_DB: ecommerce
    networks:
      - airflow
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_setup/init.sql:/docker-entrypoint-initdb.d/init.sql

  webserver: 
      environment:
        AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
